const { contextBridge, ipcRenderer } = require('electron');

const on = (ch) => (cb) => {
  const fn = (_e, data) => cb(data);
  ipcRenderer.on(ch, fn);
  return () => ipcRenderer.removeListener(ch, fn);
};

contextBridge.exposeInMainWorld('pm', {
  getState: () => ipcRenderer.invoke('get-state'),
  onState: on('state'),

  // Ventana del pollito
  onSay: on('pet:say'),
  onAnim: on('pet:anim'),
  onCursor: on('pet:cursor'),
  setIgnore: (v) => ipcRenderer.send('pet:ignore', v),
  dragStart: (p) => ipcRenderer.send('pet:drag-start', p),
  dragMove: (p) => ipcRenderer.send('pet:drag-move', p),
  dragEnd: () => ipcRenderer.send('pet:drag-end'),
  click: () => ipcRenderer.send('pet:click'),
  petted: () => ipcRenderer.send('pet:petted'),
  context: () => ipcRenderer.send('pet:context'),
  onMeeting: on('pet:meeting'),
  onPomo: on('pet:pomo'),
  onClaude: on('pet:claude'),
  // Captura rápida
  onCaptureOpen: on('capture:open'),
  captureSubmit: (text) => ipcRenderer.invoke('capture:submit', text),
  captureClose: () => ipcRenderer.send('capture:close'),
  onFocus: on('pet:focus'),

  // Panel
  onView: on('panel:view'),
  hidePanel: () => ipcRenderer.send('panel:hide'),
  openPanel: (view) => ipcRenderer.send('panel:open', view),
  chat: (text) => ipcRenderer.invoke('chat:send', text),
  feed: () => ipcRenderer.send('pet:feed'),
  pet: () => ipcRenderer.send('pet:pet'),
  rename: (name) => ipcRenderer.invoke('pet:rename', name),
  saveStandup: (d) => ipcRenderer.invoke('standup:save', d),
  saveReview: (d) => ipcRenderer.invoke('review:save', d),
  toggleTask: (date, index) => ipcRenderer.invoke('task:toggle', { date, index }),
  addTask: (text) => ipcRenderer.invoke('task:add', text),
  removeTask: (index) => ipcRenderer.invoke('task:remove', index),
  snooze: (kind) => ipcRenderer.invoke('snooze', kind),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  setToken: (t) => ipcRenderer.invoke('token:set', t),
  refreshUsage: () => ipcRenderer.invoke('usage:refresh'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  webLogin: () => ipcRenderer.invoke('web:login'),
  webLogout: () => ipcRenderer.invoke('web:logout'),
  viewChanged: (v) => ipcRenderer.send('panel:view-changed', v),
  connectAccount: (provider) => ipcRenderer.invoke('account:connect', provider),
  removeAccount: (provider) => ipcRenderer.invoke('account:remove', provider),
  saveMail: (cfg) => ipcRenderer.invoke('mail:save', cfg),
  removeMail: () => ipcRenderer.invoke('mail:remove'),
  refreshMail: () => ipcRenderer.invoke('mail:refresh'),
  saveCalendar: (url) => ipcRenderer.invoke('cal:save', url),
  removeCalendar: () => ipcRenderer.invoke('cal:remove'),
  refreshCalendar: () => ipcRenderer.invoke('cal:refresh'),
  join: (url) => ipcRenderer.send('join', url),
  pomoStart: () => ipcRenderer.send('pomo:start'),
  pomoStop: () => ipcRenderer.send('pomo:stop'),
  addReminder: (text) => ipcRenderer.invoke('reminder:add', text),
  removeReminder: (id) => ipcRenderer.send('reminder:remove', id),
  gitYesterday: () => ipcRenderer.invoke('git:yesterday'),
  gitRefresh: () => ipcRenderer.invoke('git:refresh'),
  setGithubToken: (t) => ipcRenderer.invoke('github:token', t),
  githubRefresh: () => ipcRenderer.invoke('github:refresh'),
  openPR: (url) => ipcRenderer.send('open-pr', url),
  hooksInstall: () => ipcRenderer.invoke('hooks:install'),
  hooksUninstall: () => ipcRenderer.invoke('hooks:uninstall'),
  weeklyReport: () => ipcRenderer.invoke('report:weekly'),
  dailyText: () => ipcRenderer.invoke('report:daily'),
  copy: (text) => ipcRenderer.invoke('copy', text),
  exportTimesheet: () => ipcRenderer.invoke('timesheet:export'),
  updateIntegrations: (patch) => ipcRenderer.invoke('settings:integrations', patch),
  setAiKey: (k) => ipcRenderer.invoke('ai:setKey', k),
  aiPolish: (text, kind) => ipcRenderer.invoke('ai:polish', { text, kind }),
  onThinking: on('chat:thinking'),
  shopBuy: (id) => ipcRenderer.invoke('shop:buy', id),
  shopEquip: (id) => ipcRenderer.invoke('shop:equip', id),
  shopUnequip: (slot) => ipcRenderer.invoke('shop:unequip', slot),
  stats: () => ipcRenderer.invoke('stats:get'),
  addMonitor: (url, name) => ipcRenderer.invoke('monitor:add', { url, name }),
  removeMonitor: (id) => ipcRenderer.invoke('monitor:remove', id),
  checkMonitors: () => ipcRenderer.invoke('monitor:check'),
  openMonitor: (id) => ipcRenderer.send('open-monitor', id),
  openGame: () => ipcRenderer.send('game:open'),
  gameEnd: (score) => ipcRenderer.invoke('game:end', score),
  gameClose: () => ipcRenderer.send('game:close'),
  checkUpdates: () => ipcRenderer.invoke('update:check'),
  quit: () => ipcRenderer.send('app:quit'),
});
