const { contextBridge, ipcRenderer } = require('electron');

const on = (ch) => (cb) => {
  const fn = (_e, data) => cb(data);
  ipcRenderer.on(ch, fn);
  return () => ipcRenderer.removeListener(ch, fn);
};

contextBridge.exposeInMainWorld('pm', {
  getState: () => ipcRenderer.invoke('get-state'),
  onState: on('state'),

  // Ventana del pollito
  onSay: on('pet:say'),
  onAnim: on('pet:anim'),
  onCursor: on('pet:cursor'),
  setIgnore: (v) => ipcRenderer.send('pet:ignore', v),
  dragStart: (p) => ipcRenderer.send('pet:drag-start', p),
  dragMove: (p) => ipcRenderer.send('pet:drag-move', p),
  dragEnd: () => ipcRenderer.send('pet:drag-end'),
  click: () => ipcRenderer.send('pet:click'),
  petted: () => ipcRenderer.send('pet:petted'),
  context: () => ipcRenderer.send('pet:context'),
  onMeeting: on('pet:meeting'),
  onPomo: on('pet:pomo'),
  onClaude: on('pet:claude'),
  // Captura rápida
  onCaptureOpen: on('capture:open'),
  captureSubmit: (text) => ipcRenderer.invoke('capture:submit', text),
  captureClose: () => ipcRenderer.send('capture:close'),
  onFocus: on('pet:focus'),

  // Panel
  onView: on('panel:view'),
  hidePanel: () => ipcRenderer.send('panel:hide'),
  openPanel: (view) => ipcRenderer.send('panel:open', view),
  chat: (text) => ipcRenderer.invoke('chat:send', text),
  feed: () => ipcRenderer.send('pet:feed'),
  pet: () => ipcRenderer.send('pet:pet'),
  rename: (name) => ipcRenderer.invoke('pet:rename', name),
  saveStandup: (d) => ipcRenderer.invoke('standup:save', d),
  saveReview: (d) => ipcRenderer.invoke('review:save', d),
  toggleTask: (date, index) => ipcRenderer.invoke('task:toggle', { date, index }),
  addTask: (text) => ipcRenderer.invoke('task:add', text),
  removeTask: (index) => ipcRenderer.invoke('task:remove', index),
  snooze: (kind) => ipcRenderer.invoke('snooze', kind),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  setToken: (t) => ipcRenderer.invoke('token:set', t),
  refreshUsage: () => ipcRenderer.invoke('usage:refresh'),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  webLogin: () => ipcRenderer.invoke('web:login'),
  webLogout: () => ipcRenderer.invoke('web:logout'),
  viewChanged: (v) => ipcRenderer.send('panel:view-changed', v),
  connectAccount: (provider) => ipcRenderer.invoke('account:connect', provider),
  removeAccount: (provider) => ipcRenderer.invoke('account:remove', provider),
  saveMail: (cfg) => ipcRenderer.invoke('mail:save', cfg),
  removeMail: () => ipcRenderer.invoke('mail:remove'),
  refreshMail: () => ipcRenderer.invoke('mail:refresh'),
  saveCalendar: (url) => ipcRenderer.invoke('cal:save', url),
  removeCalendar: () => ipcRenderer.invoke('cal:remove'),
  refreshCalendar: () => ipcRenderer.invoke('cal:refresh'),
  join: (url) => ipcRenderer.send('join', url),
  pomoStart: () => ipcRenderer.send('pomo:start'),
  pomoStop: () => ipcRenderer.send('pomo:stop'),
  addReminder: (text) => ipcRenderer.invoke('reminder:add', text),
  removeReminder: (id) => ipcRenderer.send('reminder:remove', id),
  gitYesterday: () => ipcRenderer.invoke('git:yesterday'),
  gitRefresh: () => ipcRenderer.invoke('git:refresh'),
  setGithubToken: (t) => ipcRenderer.invoke('github:token', t),
  githubRefresh: () => ipcRenderer.invoke('github:refresh'),
  openPR: (url) => ipcRenderer.send('open-pr', url),
  hooksInstall: () => ipcRenderer.invoke('hooks:install'),
  hooksUninstall: () => ipcRenderer.invoke('hooks:uninstall'),
  weeklyReport: () => ipcRenderer.invoke('report:weekly'),
  dailyText: () => ipcRenderer.invoke('report:daily'),
  copy: (text) => ipcRenderer.invoke('copy', text),
  exportTimesheet: () => ipcRenderer.invoke('timesheet:export'),
  updateIntegrations: (patch) => ipcRenderer.invoke('settings:integrations', patch),
  setAiKey: (k) => ipcRenderer.invoke('ai:setKey', k),
  aiPolish: (text, kind) => ipcRenderer.invoke('ai:polish', { text, kind }),
  onThinking: on('chat:thinking'),
  shopBuy: (id) => ipcRenderer.invoke('shop:buy', id),
  shopEquip: (id) => ipcRenderer.invoke('shop:equip', id),
  shopUnequip: (slot) => ipcRenderer.invoke('shop:unequip', slot),
  stats: () => ipcRenderer.invoke('stats:get'),
  addMonitor: (url, name) => ipcRenderer.invoke('monitor:add', { url, name }),
  removeMonitor: (id) => ipcRenderer.invoke('monitor:remove', id),
  checkMonitors: () => ipcRenderer.invoke('monitor:check'),
  openMonitor: (id) => ipcRenderer.send('open-monitor', id),
  openGame: () => ipcRenderer.send('game:open'),
  gameEnd: (score) => ipcRenderer.invoke('game:end', score),
  gameClose: () => ipcRenderer.send('game:close'),
  checkUpdates: () => ipcRenderer.invoke('update:check'),
  // Comandos, paleta y avisos
  command: (cmd, arg) => ipcRenderer.send('command', { cmd, arg }),
  petAction: (cmd, arg) => ipcRenderer.send('pet:action', { cmd, arg }),
  onPaletteOpen: on('palette:open'),
  paletteList: () => ipcRenderer.invoke('palette:list'),
  paletteRun: (id, arg) => ipcRenderer.invoke('palette:run', { id, arg }),
  paletteText: (text) => ipcRenderer.invoke('palette:text', text),
  paletteClose: () => ipcRenderer.send('palette:close'),
  paletteSearch: (q) => ipcRenderer.invoke('palette:search', q),
  openPalette: () => ipcRenderer.send('palette:open'),
  onChatAsk: on('chat:ask'),
  inboxRead: (id) => ipcRenderer.invoke('inbox:read', id),
  inboxClear: () => ipcRenderer.invoke('inbox:clear'),
  // Ventanas
  openSettings: (section) => ipcRenderer.send('settings:open', section),
  closeSettings: () => ipcRenderer.send('settings:close'),
  onSettingsSection: on('settings:section'),
  openAbout: () => ipcRenderer.send('about:open'),
  closeAbout: () => ipcRenderer.send('about:close'),
  openDataDir: () => ipcRenderer.send('open-data-dir'),
  // Apariencia, privacidad y datos
  setAppearance: (patch) => ipcRenderer.invoke('appearance:set', patch),
  pauseTracking: (minutes) => ipcRenderer.invoke('tracking:pause', minutes),
  setPrivacy: (patch) => ipcRenderer.invoke('privacy:set', patch),
  exportData: () => ipcRenderer.invoke('data:export'),
  importData: () => ipcRenderer.invoke('data:import'),
  deleteData: () => ipcRenderer.invoke('data:delete'),
  setFlags: (patch) => ipcRenderer.invoke('flags:set', patch),
  // Tareas editables
  editTask: (index, text) => ipcRenderer.invoke('task:edit', { index, text }),
  moveTask: (from, to) => ipcRenderer.invoke('task:move', { from, to }),
  updateTask: (index, patch) => ipcRenderer.invoke('task:update', { index, patch }),
  restoreTask: (index, task) => ipcRenderer.invoke('task:restore', { index, task }),
  taskTimer: (index, action) => ipcRenderer.invoke('task:timer', { index, action }),
  restoreReminder: (r) => ipcRenderer.invoke('reminder:restore', r),
  // Mascota
  hover: (on) => ipcRenderer.send('pet:hover', on),
  onDock: on('pet:dock'),
  onPlay: on('pet:play'),
  onStroll: on('pet:stroll'),
  setSpecies: (sp) => ipcRenderer.invoke('pet:species', sp),
  play: (kind) => ipcRenderer.invoke('pet:play', kind),
  // Diario de Claude, prompts, bloques, objetivos, hábitos, notas
  journalAi: (which) => ipcRenderer.invoke('journal:ai', which),
  journalRefresh: () => ipcRenderer.invoke('journal:refresh'),
  promptCopy: (id) => ipcRenderer.invoke('prompts:copy', id),
  promptSave: (p) => ipcRenderer.invoke('prompts:save', p),
  promptDelete: (id) => ipcRenderer.invoke('prompts:delete', id),
  setBlocks: (list) => ipcRenderer.invoke('blocks:set', list),
  goalSave: (g) => ipcRenderer.invoke('goals:save', g),
  goalDelete: (id) => ipcRenderer.invoke('goals:delete', id),
  habitStep: (id, delta) => ipcRenderer.invoke('habits:step', { id, delta }),
  habitSave: (h) => ipcRenderer.invoke('habits:save', h),
  habitDelete: (id) => ipcRenderer.invoke('habits:delete', id),
  setNotes: (text) => ipcRenderer.invoke('notes:set', text),
  searchNotes: (q) => ipcRenderer.invoke('notes:search', q),
  // Copias de seguridad e informe mensual
  backupNow: () => ipcRenderer.invoke('backup:now'),
  backupDir: () => ipcRenderer.invoke('backup:dir'),
  backupOpen: () => ipcRenderer.invoke('backup:open'),
  monthlyPdf: (which) => ipcRenderer.invoke('monthly:pdf', which),
  // Recurrentes, plantillas, modo foco y diagnóstico
  addRecurring: (r) => ipcRenderer.invoke('recurring:add', r),
  deleteRecurring: (id) => ipcRenderer.invoke('recurring:delete', id),
  applyTemplate: (id) => ipcRenderer.invoke('templates:apply', id),
  saveTemplate: (name) => ipcRenderer.invoke('templates:save', name),
  deleteTemplate: (id) => ipcRenderer.invoke('templates:delete', id),
  focusStart: (min) => ipcRenderer.invoke('focus:start', min),
  focusStop: () => ipcRenderer.invoke('focus:stop'),
  onFocusMode: on('pet:focusmode'),
  diagGet: () => ipcRenderer.invoke('diag:get'),
  diagCopy: () => ipcRenderer.invoke('diag:copy'),
  diagOpen: () => ipcRenderer.invoke('diag:open'),
  reportError: (msg) => ipcRenderer.send('diag:error', msg),
  // Programación, organización y vida del pollito
  queueAdd: (text, project) => ipcRenderer.invoke('queue:add', { text, project }),
  queueRemove: (id) => ipcRenderer.invoke('queue:remove', id),
  queueNext: (project) => ipcRenderer.invoke('queue:next', project),
  prioritize: (withBlocks) => ipcRenderer.invoke('day:prioritize', withBlocks),
  splitTask: (i) => ipcRenderer.invoke('task:split', i),
  milestoneSave: (m) => ipcRenderer.invoke('milestone:save', m),
  milestoneDone: (id, done) => ipcRenderer.invoke('milestone:done', { id, done }),
  milestoneDelete: (id) => ipcRenderer.invoke('milestone:delete', id),
  fridayData: () => ipcRenderer.invoke('friday:data'),
  fridaySave: (r) => ipcRenderer.invoke('friday:save', r),
  buyHome: (id) => ipcRenderer.invoke('home:buy', id),
  writeDiary: () => ipcRenderer.invoke('diary:write'),
  pushCheck: () => ipcRenderer.invoke('push:check'),
  setBackupPass: (p) => ipcRenderer.invoke('backup:setPass', p),
  onMusic: on('pet:music'),
  audioResult: (r) => ipcRenderer.send('audio:result', r),
  setIntegration: (what, on) => ipcRenderer.invoke('integrations:set', { what, on }),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  syncDir: () => ipcRenderer.invoke('sync:dir'),
  exportMarkdown: () => ipcRenderer.invoke('export:md'),
  exportIcs: () => ipcRenderer.invoke('export:ics'),
  profileAdd: (name, emoji) => ipcRenderer.invoke('profile:add', { name, emoji }),
  profileSwitch: (id) => ipcRenderer.invoke('profile:switch', id),
  profileRemove: (id) => ipcRenderer.invoke('profile:remove', id),
  setCli: (on) => ipcRenderer.invoke('cli:set', on),
  updateProjectMemory: (repo) => ipcRenderer.invoke('projmem:update', repo),
  gitRepos: () => ipcRenderer.invoke('git:repos'),
  onHatch: on('pet:hatch'),
  quit: () => ipcRenderer.send('app:quit'),
});
